apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jenkins
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: CASC_JENKINS_CONFIG
              value: /var/jenkins_home/casc_configs/jcasc.yaml
            - name: JAVA_OPTS
              value: "{{ .Values.env.JAVA_OPTS }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jcasc-config
              mountPath: /var/jenkins_home/casc_configs
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-jenkins
        - name: jcasc-config
          configMap:
            name: {{ .Release.Name }}-jcasc
