apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sfsturbo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sfsturbo
  csi:
    driver: sfsturbo.csi.everest.io
    fsType: nfs
    volumeHandle: "2624cc97-f988-4ed9-a5cc-709a7c65929b"   # Tu SFS ID
