apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sfsturbo
provisioner: sfsturbo.csi.everest.io
parameters:
  sfsType: TURBO        # Si tu SFS es TURBO
  fsType: nfs           # SFS Turbo soporta nfs
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - vers=3
