replicaCount: 2

image:
  registry: swr.la-south-2.myhuaweicloud.com
  namespace: cce-basic-app
  repository: app-basic-java
  tag: "2.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: default-secret

app:
  name: wl-java-app
  version: v1
  containerPort: 8081  # Puerto interno del contenedor
  healthPath: /app-java/healthCheck

service:
  name: sr-java-app
  type: LoadBalancer
  port: 80            # Puerto externo del ELB (acceso p√∫blico)
  targetPort: 8081    # Puerto interno del contenedor

elb:
  #id: "c1cb8fdd-4d80-42c0-94d2-9436854c1595"
  id: ""
  type: performance
  bandwidth: 5
  eipType: "5_bgp"
  bandwidthShareType: "PER"

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"