apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-java
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /app-java
            pathType: Prefix
            backend:
              service:
                name: sr-java-app
                port:
                  number: 8081
