apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.version }}
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: {{ .Values.elb.id | quote }}
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
    kubernetes.io/elb.health-check-flag: "on"

spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.version }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
