{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.pvcName }}
  namespace: {{ .Values.controller.namespace }}
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: {{ .Values.persistence.storageProvisioner }}
    everest.io/enterprise-project-id: {{ .Values.enterpriseProjectId }}  
spec:
  accessModes:
  - ReadWriteMany                  
  resources:
    requests:
      storage: {{ .Values.persistence.size }}            
  storageClassName: {{ .Values.persistence.className }}      
  volumeName: {{ .Values.persistence.pvName }}    
{{- end }}
