{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.pvcName }}
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: {{ .Values.persistence.storage-provisioner }}
    everest.io/enterprise-project-id: {{ .Values.enterpriseProjectId }}   # Enterprise project ID of the SFS Turbo volume
spec:
  accessModes:
  - ReadWriteMany                  # The value must be ReadWriteMany for SFS Turbo.
  resources:
    requests:
      storage: {{ .Values.persistence.size }}               # SFS Turbo volume capacity.
  storageClassName: {{ .Values.persistence.className }}       # StorageClass name of the SFS Turbo file system, which must be the same as that of the PV
  volumeName: {{ .Values.persistence.pvName }}    # PV name
{{- end }}