apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sfs-turbo-sc
provisioner: everest-csi-provisioner
parameters:
  csi.storage.k8s.io/csi-driver-name: sfsturbo.csi.everest.io
  type: sfsturbo
reclaimPolicy: Retain
volumeBindingMode: Immediate
