version: "3.9"

services:
  jenkins:
    image: jenkins-hwc:1.0
    container_name: jenkins-hwc
    platform: linux/amd64

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_data:/var/jenkins_home
      - ./casc.yaml:/var/jenkins_home/casc.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock  # Monta el socket Docker del host

    env_file:
      - ./secrets.env

    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc.yaml
      DOCKER_HOST: unix:///var/run/docker.sock  # Opcional, asegura que Jenkins use Docker

    user: root  # Para poder acceder al socket la primera vez
    privileged: true  # Permite DinD si lo necesitas en alg√∫n job

    restart: unless-stopped

volumes:
  jenkins_data:
