apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sfs-static-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""   # IMPORTANTE
  resources:
    requests:
      storage: 10Gi
