apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-acceso-huaweicloud
  namespace: default
  annotations:
    # La clave exacta es esta, sin protocolos (sin http://)
    ://huaweicloud.com: "cce_node_agency"
