apiVersion: v2
name: jenkins
description: Helm chart para desplegar Jenkins Controller en Huawei CCE con agentes ef√≠meros SSH
type: application
version: 0.1.0
appVersion: "2.452.1"

keywords:
  - jenkins
  - ci
  - cd
  - cce
  - huaweicloud
  - ssh
  - ephemeral

maintainers:
  - name: Alejandro More
    email: alejandro@example.com

# Dependencias opcionales
dependencies: []
