jenkins:
  systemMessage: "Jenkins on Huawei CCE - Agents Ef√≠meros"

  numExecutors: 0

  clouds:
    - kubernetes:
        name: "kubernetes"
        namespace: "jenkins"
        serverUrl: "https://kubernetes.default"
        jenkinsUrl: "http://{{ .Release.Name }}-jenkins:8080"
        containerCapStr: "10"
        retentionTimeout: 5

        templates:
          - name: "default"
            label: "k8s-agent"
            serviceAccount: "default"
            idleMinutes: 5
            containers:
              - name: "jnlp"
                image: "jenkins/inbound-agent:latest"
                args: "^${computer.jnlpmac} ^${computer.name}"
                resourceRequestCpu: "200m"
                resourceRequestMemory: "256Mi"
                resourceLimitCpu: "500m"
                resourceLimitMemory: "512Mi"
