configServer:
  replicaCount: 1
  port: 8888
  image:
    registry: swr.la-south-2.myhuaweicloud.com
    organization: cce-jenkins-integration-organization
    repository: config-server-hw
    tag: "1.2.3"
    pullPolicy: Always
  secretName: secret-config-catalog

catalogError:
  replicaCount: 1
  port: 50051
  image:
    registry: swr.la-south-2.myhuaweicloud.com
    organization: cce-jenkins-integration-organization
    repository: catalog-error-hw
    tag: "1.0"
    pullPolicy: Always
  secretName: secret-config-catalog

demoClient:
  replicaCount: 1
  image:
    registry: swr.la-south-2.myhuaweicloud.com
    organization: cce-jenkins-integration-organization
    repository: demo-client
    tag: "1.0"
    pullPolicy: Always
  secretName: secret-config-catalog
  port: 80
  targetPort: 8081

elb:
  id: ""                # Se inyecta din√°micamente desde Jenkins