apiVersion: ENC[AES256_GCM,data:fvI=,iv:nq+9aRKXWZkK84ONXOzl8NZjzi044C75yNO1a7VL+SE=,tag:+3FkR2SfZfTkJjdblM36oA==,type:str]
kind: ENC[AES256_GCM,data:V3Cch/nb,iv:/LjRQAv2Bqto3olGKnsZYdJZCP20fV2HPGOPANruq6c=,tag:VO2/BJGzsA7RdCuCW9XdWQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XjOcA7V5G4FvaWPFDO91IAoQsgnt,iv:yaVEWO6xOcZxCM9kuZR7eiQJ1WdAxBr9ThHbbZGjvsw=,tag:6G3hyk88V9hmc/Y+0ZW2OQ==,type:str]
type: ENC[AES256_GCM,data:FfR1FS/M,iv:1UiAkIyIRFbpjRQXR2D/M+sK2erELe35fSG1KGyYDDo=,tag:G6Fz7p/QVYur6XRph3gm7A==,type:str]
stringData:
    GIT_URI: ENC[AES256_GCM,data:LUxF00XtIiFW34X/ao/n4oqTIPwTD3oy1iqbc/rU6ZWhYXdJuz2qjjS8Z3fsfpVGZr+k8Q6dPiCIThqnVTCryD+Ilo7m,iv:jFRzTmwDRuTAiHRIRifAJgbCrE0CvMrr4QccotHUiiY=,tag:gThjxs/fqRX1hvLglzAmSg==,type:str]
    GIT_USERNAME: ENC[AES256_GCM,data:8aMzqJcLTNw4nqmKgw==,iv:+ksTBG0n25+aAV8adCwmGGlXoi8KCPb/sTqdbMjbI00=,tag:mNxhlBHc+IUPF44ocDi4yw==,type:str]
    GIT_TOKEN: ENC[AES256_GCM,data:sT8Md+eo15c93yFDxcCIdJ6ox+ziUCaEF5lDvVxz1PNXjvEGJH5b4x6GMAoHEkQxvQqIvZ4ICw+hfxpjBghW8SOEBsoZToswpreYY1o67lsk2YTsCnD8ce16vTGr9Cs4gbQRIfk50DaV8z0WiH7vgxpzm8JKzSrDbfG2xTN5OyJ4fShJSFU9nSVS5JV/nkM397Pl2lCDulT7tnsSX92QZfs+b2xM7zR2V/dPYq1kMnwgm0B7DqiwdZv1349CFANx,iv:OP4Ze1Y56nvq5OF+I5yGIf6vqxi+luQlp5SQ2a3/kEI=,tag:7Cuy7G6BduvtJ7zn+UKGtQ==,type:str]
    HUAWEI_CLOUD_REGION: ENC[AES256_GCM,data:/0BR7ou9XqCdVA==,iv:KSHl/JleP5/16ExF/PpQpf/d1EGgv9iDioe7U3AF+sI=,tag:PUIl7w62u6ZlUnvTzqSYDg==,type:str]
    HUAWEI_CLOUD_PROJECT_ID: ENC[AES256_GCM,data:ubO4VinR/JOg1Rf4/PQyogM1Cn0v/7pbI7zVjXza+qo=,iv:beRaw6L+pMaOQBaxpTWHDJ74/KnEkQn9DSjMWP51Cxs=,tag:PB8D/h50+P7ZwNa5Y97eFA==,type:str]
    HUAWEI_CLOUD_CREDENTIALS: ENC[AES256_GCM,data:gm68eQdUCQqwcPAWyqeKHiBN75qOvBLpRgmsEAHl3xbyi5fzUGEjQjuDCpX71gAAnVFx,iv:F1Qvg1nvr4d3oOp5WjVEHjGyToLOiTBh3ff0DvHCvWc=,tag:3lNtviR/3zD0XclHNUF9IQ==,type:str]
    HUAWEI_CLOUD_SECRET_NAME: ENC[AES256_GCM,data:uOShB6GDFjESb25O7B2v,iv:TZnNLxwXoD+6w6BnAkI5m+v0MXqz+IohDKMMiFgO2Bo=,tag:98SJLPgcBqp810xcuZyWCA==,type:str]
    SCHEDULE_TIME: ENC[AES256_GCM,data:vQM=,iv:94R9JnautbzPWJVx1lUrdvcnjwCODbaGVh4akfHCRcg=,tag:kL96B4Fr7V6yslledJlIVg==,type:str]
    CATALOG_ERROR_PROFILE: ENC[AES256_GCM,data:hW5D2r4Z,iv:yyLUGevEAmSK+JYLDH27WJpM6mwOSLXaPtLRsmopw/0=,tag:Ll3xYf7jIL7oDr5jD8KZZQ==,type:str]
    HUAWEI_END_POINT: ENC[AES256_GCM,data:we3Fu4aaczH7QAwARkyF5WaSSQzZj2fpa1yQm1IfTrwaB2aeapPYS90=,iv:lCsjPqsXY0/nV8WF2dEbW25yAB/G7MKrWc8J+YXU7Zc=,tag:I+oVR2bKjNazCBdx+TJF9Q==,type:str]
    HUAWEI_BUCKET_NAME: ENC[AES256_GCM,data:9KeZ8LdZAS6POgVOHP/eh4Ad3cOMYg==,iv:W/dzVNTQODg2P2fwJbKxThPrDT7odjPqLEJxZC3iasM=,tag:0p4QHLjjVLIh0v5uTsExhg==,type:str]
    FILE_NAME: ENC[AES256_GCM,data:vGnDZgRDK7NoZuLk+9xoUhnZM57jD76ECw==,iv:24BF8vH8JDlBtfP5O7fKYl9ztGxIFX8QBD6WNFRDfCU=,tag:8yCvxuFIjG36DTjTMaDT5A==,type:str]
sops:
    lastmodified: "2026-02-17T23:41:44Z"
    mac: ENC[AES256_GCM,data:Tp1oYQm1uowVqadLF+HNU94NLbKnxmtpV01Lp2QHXRRVwtxf/IbQ6rr7o9Dujh93BdZ2eAdP8sUlGXF+e1FKw2MF3uFxWMQGDH4m7l9nUlq06qFPPr+rQob5FjVRm5ScmEZexl2b1evyKUeNCIsza3ajNW9EQd5hhuBVWzmuUA8=,iv:h7YthTnC6fWGfG7Nf+QXp3U3vSlw8kwuw5kYWwMg3gM=,tag:zPMETgn26e+yr6mL79ZQnA==,type:str]
    pgp:
        - created_at: "2026-02-17T23:41:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8owemZ0jy2tAQ/+OMpYciIOEIUrRArqsLdPwWJJYtyip+MSXvAf+xzy39j/
            qlmaC0lMX84/TnGTBQJG4pGbXzcrUffO3LIlJHjgFs8VNvt6BmgqofrnwXEz/BEw
            ozf+ZohdMItqdrpTCF3SZ9Z7P0dCZdCQW2NOyurnDnsQX7mzk6MNXPLChzfoZRO/
            TseYXwnlkLR9Jffxtfrd9l+/4GsNBLusDJt2Cu/8ptY52ClGL+HrxoEDsOln/oo5
            Q4UzewKfxkvX1vVXtdgR5+Df+KUcG3pFyKhBwTu4G4aiyyuJ+wYjNnUZooE6l8GU
            4+9uyzwvMCAH/T8/IbnDe1ob/9Dg31Vp1f1ciGFZBfbtZTJyMCdobLIwbZ5/ANeh
            zaDLtL6nUuKhtkAczpdmieMIw/UDEqL4Lj1txwBrn27nSZsf4nNq1o67mYpot/Xk
            +DeRWmOUd66ayDwuh0pkyZlfIwaHlV9I4g/sG15qckBFMUG/+duYscjDDrKfTXWJ
            esvw4pvoSL9OgPEpvKkKCcUXE87GCjC4tgfUUEYald1sxps2QzoIkbw9HBkdG3Ga
            RwYHDotIiHOx34Ug+P/7ztW4/cAcIgWW7ctV8wr4uGSj0ldprgyfMID5PeZhT9xG
            GVHhastPP8o5RxlG8wveG4NrPXvsWkUfhfAEo4lJX+0LWQ2wyLSEX1SsT3RKvD/S
            XgHKt1Qyl3mTnutTUzHnD+KFOmuEN4lhcgwNwHaosZ3pUzknQvs2IULHRlGUITP6
            SfOG9Jl2y+NeyR1DJGGqhyRH/JhKilcnVTzguIOi44y/oxPT3m/1TgiqrRNl1+k=
            =TgXc
            -----END PGP MESSAGE-----
          fp: 1BBD53D0524D1B602D11E7EEAA3728A191FFF76D
    unencrypted_suffix: _unencrypted
    version: 3.11.0
