apiVersion: ENC[AES256_GCM,data:2iE=,iv:u4w0f9VRuSuCbD9/RISsDzoOscj0HXhrmgM3jjPB/sg=,tag:o9TJbYqTSM/zkeGxpqo+aQ==,type:str]
kind: ENC[AES256_GCM,data:/7pB2cKo,iv:RKiShRPtfm4ZLjaZYS1tLo6joJWZFbDDWcU8Ei6kHtU=,tag:H/ZqBaJ19M6zHGNgIfYn3Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SYnaL2HBuLxD1ul4ZHQ01s5+oX2O,iv:N3NiNkA3IfY4Cv4uSGt9gW0o+js0UPs5pcaraVW1bmw=,tag:UJjRXqNVfXNfZQz+vz8k6w==,type:str]
type: ENC[AES256_GCM,data:91zERwjH,iv:CriNNDXoFlpWjenKcCpuM9bluouqbptYnrgeJpyhE+Q=,tag:RAGeborZSpcv5IMc2FJjBw==,type:str]
stringData:
    GIT_URI: ENC[AES256_GCM,data:1SxaW4IVt87KUEvABo2OveHVuF88qOGqcLx038Km+mfGsNEXmYIOLuFPvXXsFHYGhIoT+hiTmUjYCW8cIPOqPvjlnSEv,iv:9LaldIp9jE5dl+6Jqt7v94xUv8rtFH5M561doUmx4ck=,tag:jtIXEpl81FtTNnCyPgDhug==,type:str]
    GIT_USERNAME: ENC[AES256_GCM,data:84lVEyCo2dZfqGxtyQ==,iv:thkDKH7nPMuhjfnM/sKjqx1izRMu28qopDuv1c+w1+4=,tag:+nj1c0GSA7yHhf/y49WCLw==,type:str]
    GIT_TOKEN: ENC[AES256_GCM,data:4eRcBPyClMwaGyNIkrSyWOutC5t0IsP+0oUoAaAfqQNDMpXqtqEUNaJyOJHjSFPcFRWUg5iQCrwb7c0snKwnW9mEMG3A0lt2PIo0C6LQG86kq8gLx1CYFpg1eOl4PVRiCC81GAK5SMHJmKlnqZcEvhbvYFZBj0sMcCIlEE2/y+Qbf7BZHhJALKDdp7Lpq5MOdzR8+Js4RISlHs4h7UMb8BowPNIJYRQhvmv4J15pLpOZGVbYmMxNwSiYjzz9UPsz,iv:utNUpyZVfVpabN46hthaKUMUS0omPqiAqVGfTkGKWLU=,tag:DucFCD6bXAfaghweFeEehQ==,type:str]
    HUAWEI_CLOUD_REGION: ENC[AES256_GCM,data:qm/TDXwj/eFPfA==,iv:eAFl5pARsVpXLgOwjFhMCMCH82TSGVkqjt9JDypGkmg=,tag:Mw8TEBwzwuNSj1tISOIq6A==,type:str]
    HUAWEI_CLOUD_PROJECT_ID: ENC[AES256_GCM,data:C1CBYgWOl4WqixDFBR5/YLZuY8f0E7WgfNRu7+2Q4WY=,iv:wgLzLJNVHJN/EdLFO4xYPTix+8XYCQC9EXNv1rA/VhU=,tag:3/vIaxpVWGyVEUT6Cq1cWw==,type:str]
    HUAWEI_CLOUD_AK: ENC[AES256_GCM,data:l2U6zESQrpAFgNZ6GbWR1DBczdc=,iv:bj0tlJeDv5wVQkkIP7xqSlIsV3byCPKOvwtMIycyHOY=,tag:DVdcpcY7YVlJVRcV1Sb2LA==,type:str]
    HUAWEI_CLOUD_SK: ENC[AES256_GCM,data:3YVqzu3Tk5MrveHyZlNqHMKaa/Xxd7FSWWpuaqAeM9+IPkCyRLWj/g==,iv:qHGojnVlyJ9PG8oWf/Q+LJxveKa2BAjzbF61olMMYi4=,tag:203uscbn1Fx/Stth/N5mcQ==,type:str]
    HUAWEI_CLOUD_SECRET_NAME: ENC[AES256_GCM,data:CskfdJew7mPAEbLSjNHr,iv:Rxj6HYPWLxDoykqrzMMjAG/D6z14nd/5+b3SCXQW0A4=,tag:yQtUuShzNn6ztntvMdGQ6g==,type:str]
    SCHEDULE_TIME: ENC[AES256_GCM,data:PGw=,iv:qjQNDLmhwDYMpjYswgqjpgH5AQx/IZsfTpnoDDBgQ8M=,tag:t763olev7M0KH128R9Rwlg==,type:str]
    CATALOG_ERROR_PROFILE: ENC[AES256_GCM,data:knpCveOM,iv:MnlILjKNwSCv9cNQFMJgNlCeXDwctkz8vC5cJsu47DM=,tag:qvUs5HwM94EePmegxe8HiQ==,type:str]
    HUAWEI_END_POINT: ENC[AES256_GCM,data:SQ9G+EB3qk2DhviVo+Pf5m5XEo75WkdSL5IJm5t3jdtPPLk0hB8dw2E=,iv:1BNxC+PJk7KCsnogI24Fq+6/1zKXezlpeNXapvlx2k8=,tag:e8b3I8X9Z9M1gnQiga3rKQ==,type:str]
    HUAWEI_BUCKET_NAME: ENC[AES256_GCM,data:NIshu1QCAdBqTuH7it5TFkXWce4GDg==,iv:Rk9m6chpyP9CKa5GnXKj4V8Dz50S97NCpg6+x/sKbbo=,tag:Ldxc3s7FDFMAOWGrMkASfg==,type:str]
    FILE_NAME: ENC[AES256_GCM,data:H61EuRx8UdhaGcUgkSkESIhwvHA/TC3k3Q==,iv:GHHV2vezsZ2tng0T3j+B02Od3n1N0YAH9CWK8jMPuos=,tag:GLL4L9FG9cc0GTCYkbtm+g==,type:str]
sops:
    lastmodified: "2026-02-13T14:49:50Z"
    mac: ENC[AES256_GCM,data:s2mCJmiXG6N7Fv6WaVBZVrayaO4gm3Y9yxeWNf2HU6ASvejUggfqcjWtS85b8Siq3NZmpEhUFJMiT4zTPvGhuAFyRVGmqttsCdSbx6kzpm05pM0m9+b0HEsVKhdVl+Lm6BcdV2wPaXAQMdOGyYKwihEa8IKxDXLVq4fhMKDHXtk=,iv:XEseLW3mu8AgNJtnXvtshdgwWbsVoSxgU+fRe9TeEEQ=,tag:LTpqdU8QtLwnFixZ4Lm6xA==,type:str]
    pgp:
        - created_at: "2026-02-13T14:49:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8owemZ0jy2tAQ/8D7EgCY8/9YRbmrctR60DDXM8p4u1aJ4zMUuiLjPWohDm
            X+tg3FZ8iLDcdPypFrtopMZgaVATT3gWfP3TUC1IJB5ufoijGXyeV9Gzqrw17NoH
            8iSHEYk1iTmdpC74LikI99JZRCN974n1b2flzpcQHfEcea6Hazi+YZChEgCHXWE+
            h+W2T5N+wPWrDBKNBk0POeYBM+iXDv04UvS5HxWgfI8/xo2Q9zjSvJjIat9HwZAY
            F/TvuGK61dmG5azLfU1tt5HHQZCpjGuJlpGH/O1jy2GKjWnbjg0wi8wsLkjRza2L
            NGEexb5qprhIkKse8tpsbWOANHeS7YTmsE/iL3sAUKnOjeC0RpkP3M1QjHYGQu54
            RBmjJ6Mceq92bhBvhOJ206ojEpRMUsZ0TJ0zfCTEuxPcuYIXX3mebW2zwrfoRgEA
            ofl4VZO9tCfRyNApegrKAfvU4jkPqsv+jyzqeWGfSqyz5w7nGjiLpSoq1gDRsr5U
            36ZGy6jNFjSCbFznXu5f+jtFrZS0Uuas4PIIvwdtcAHPb8l8IPmMsSnHHxwkLpIv
            r9JMqNQsY1hcJKE+CY07DcEFJ2ivfzWGhSuLXBr60lroh5SMm7SPdD97/YzuekE/
            9iyqy8ejIk09vNMXbLaCAhG4mdKRoyj+OE6MAK6rsU5dOVU8FCS+C9Fm+32ts8DS
            XAH7hTOBQYJCgAApfXggDFLiDxtTf8we1ZcysyB9SqWzNZsdf8rosqPumwClsbPx
            PzvJiF5gCh9XO9WHnau1PFkm0iATrJLyFLEHUTjvylITPVtiK2vG3gK9P88C
            =1jd2
            -----END PGP MESSAGE-----
          fp: 1BBD53D0524D1B602D11E7EEAA3728A191FFF76D
    unencrypted_suffix: _unencrypted
    version: 3.11.0
