apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-test
  template:
    metadata:
      labels:
        app: pod-test
    spec:
      serviceAccountName: sa-app-dev-dew
      containers:
      - name: pod-test
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "sleep infinity"]

        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: app-secret-from-csms
              key: PORT
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret-from-csms
              key: PASSWORD
        - name: URL
          valueFrom:
            secretKeyRef:
              name: app-secret-from-csms
              key: URL
        - name: USUARIO
          valueFrom:
            secretKeyRef:
              name: app-secret-from-csms
              key: USUARIO

        volumeMounts:
        - name: secrets-store-inline
          mountPath: /mnt/secrets-store
          readOnly: true

      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          fsType: ext4
          volumeAttributes:
            secretProviderClass: "app-dev-huawei-dew"