apiVersion: v1
kind: Secret
metadata:
  name: secrets-store-creds
  namespace: default
type: Opaque
stringData:
  access_key: 8ENLOAE2QCECKCRKANEU
  secret_key: vddTKjKuG8hcNGOb1cYv3jZ03RLlkOFEEhEHphl8