apiVersion: v1
kind: Service
metadata:
  name: demo-client
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: {{ .Values.elb.id | quote }}
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
    kubernetes.io/elb.health-check-flag: "on"
spec:
  selector:
    app: demo-client
  ports:
    - protocol: TCP
      port: {{ .Values.demoClient.port }}
      targetPort: {{ .Values.demoClient.port }}
  type: LoadBalancer