controller:
  image: "jenkins/jenkins:lts"
  tag: "lts"
  installPlugins:
    - kubernetes:1.39.1
    - workflow-aggregator:2.7
    - git:4.10.0
    - configuration-as-code:1.56
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  namespace: jenkins
  adminUser: "admin"                      # default user
  adminPassword: "P@ssw0rdSecure123!"     # default password

deployment:
  name: dp-jenkins-master
  version: v1
  containerPort: 8080
  replicas: 1

service:
  name: sr-jenkins-master
  type: LoadBalancer
  port: 80
  targetPort: 8080

elb:
  elbId: ""               # Se inyecta din√°micamente desde Jenkins
  type: performance
  bandwidth: 5
  eipType: "5_bgp"
  bandwidthShareType: "PER"

persistence:
  enabled: true
  pvName: pv-jenkins
  pvcName: pvc-jenkins
  #sfsId: ""               # se inyecta por --set
  #sfsTurboSharedPath: ""  # se inyecta por --set  
  size: 50Gi
  #storageProvisioner: everest-csi-provisioner
  className: csi-sfsturbo
  #driver: sfsturbo.csi.everest.io

enterpriseProjectId: ""  # se inyecta por --set

agent:
  enabled: false
