apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-obs
  namespace: default
  annotations:
    ://huaweicloud.com: "cce-workload-agency"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-dew
  namespace: default
  annotations:
    ://huaweicloud.com: "cce-workload-agency"
