apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-obs
  namespace: default
  annotations:
    iam.huaweicloud.com/agency: "workload-agency"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-dew
  namespace: default
  annotations:
    iam.huaweicloud.com/agency: "workload-agency"
