apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-obs
  annotations:
    # Referencia informativa del rol que asume en IAM
    #://iam.huaweicloud.com: "ecs-obs-dew-agency"
    huaweicloud.com/agency-name: "cce-workload-agency"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-dew
  annotations:
    # Referencia informativa del rol que asume en IAM
    #://iam.huaweicloud.com: "ecs-obs-dew-agency"
    huaweicloud.com/agency-name: "cce-workload-agency"
