replicaCount: 2

image:
  registry: swr.la-south-2.myhuaweicloud.com
  namespace: cce-basic-app
  repository: app-basic-java
  tag: "2.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: default-secret

app:
  name: wl-java-app
  version: v1
  containerPort: 8081
  healthPath: /app-java/healthCheck   # Se puede sobrescribir desde Jenkins

service:
  name: sr-java-app
  type: LoadBalancer
  port: 80
  targetPort: 8081

elb:
  id: ""                # Se inyecta din√°micamente desde Jenkins
  type: performance
  bandwidth: 5
  eipType: "5_bgp"
  bandwidthShareType: "PER"

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
