apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
